export let prod=0;
export let pay = 0;
export let estado=0;
export let subto=0;
export let cuenta_tax=0;
export let cantidad = 0;
export let cantidad_total=0;
export let med_pago = 0;
export const items = [];
export const productos =   [];
export const tipos = [];
export const precios = [];
export const resumen_product=[];
export const resumen_type = []
export const resumen_price = [];
export const resumen_qty = [];